kind: pipeline
name: default

clone:
  skip_verify: true

volumes:
- name: artefacts
  host:
    path: artefacts

steps:
- name: build
  image: node:12
  volumes:
  - name: artefacts
    path: /artefacts
  commands:
    - npm ci
    - cp -r * /artefacts
- name: deploy
  image: amaysim/serverless:1.72.0
  volumes:
  - name: artefacts
    path: /artefacts
  environment:
    AWS_ACCESS_KEY_ID:
      from_secret: aws_access_key_id
    AWS_SECRET_ACCESS_KEY:
      from_secret: aws_secret_access_key
  commands:
    - cd /artefacts
    - SLS_DEBUG=1 sls deploy --verbose
# - name: notify
#   image: drillster/drone-email
#   settings:
#     host:
#     skip_verify: true
#     from:
#   when:
#     status:
#     - changed
#     - failure
