version: '3'

services:
  drone-server:
    image: drone/drone:1
    hostname: drone-ci
    container_name: drone-ci
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/drone:/data
    environment:
      - DRONE_GITHUB_CLIENT_ID=
      - DRONE_GITHUB_CLIENT_SECRET=
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=localhost:3080
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=d41f2f9d5bb2d992f3328c8b93e51432
      - DRONE_TLS_AUTOCERT=false

  drone-runner:
    image: drone/drone-runner-docker:1
    hostname: drone-runner
    container_name: drone-runner
    ports:
      - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=localhost:80
      - DRONE_RPC_SECRET=d41f2f9d5bb2d992f3328c8b93e51432
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=${HOSTNAME}
