service: sdd-filtering-demo

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: eu-west-2
    apiGateway.shouldStartNameWithService: true

functions:
    app:
        name: API
        handler: index.handler
        events:
            - http: GET /
            - http: 'GET /{proxy+}'
    app:
        name: DynamoToElastic
        handler: d2e.handler
        events:
            - stream:
                type: dynamodb
                batchSize: 1
                enabled: true
                arn: { "Fn::GetAtt": ["SDD-Driver-DynamoDB", "StreamArn"] }

resources:
    Resources:
        SDD-Driver-DynamoDB:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: SDD-Driver
                AttributeDefinitions:
                    - AttributeName: DrivingLicenseNumber
                      AttributeType: S
                KeySchema:
                    - AttributeName: DrivingLicenseNumber
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST
                StreamSpecification:
                  StreamViewType: NEW_IMAGE
