service: sdd-filtering-demo

provider:
    name: aws
    runtime: nodejs12.x
    stage: dev
    region: us-east-1

functions:
    app:
        handler: index.handler
        events:
            - http: GET /
            - http: 'GET /{proxy+}'

resources:
    Resources:
        DynamoDB:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: Driver
                AttributeDefinitions:
                    - AttributeName: DrivingLicenseNumber
                      AttributeType: S
                KeySchema:
                    - AttributeName: DrivingLicenseNumber
                      KeyType: HASH
                BillingMode: PAY_PER_REQUEST 